### ISSUE TITLE
[0.25] Set up the repository on GitHub and use Gitflow

### ISSUE THREAD

**Issue by MarcoDDM** [MarcoDDM/recipeapp#3]

**Comment by topeogunleye** [comment]
Subject: Code Review Comment - Provide Link to Previous Pull Request

Hi @MarcoDDM, @Felipe-Perez-Ferraro,

Thanks for submitting your code for review. Before proceeding, could you please provide the link to the previous pull request on which you received a review? This will help in maintaining context and understanding the changes made based on the previous feedback.

Including the link to the prior pull request allows reviewers to have a comprehensive view of the development history and ensures that the feedback provided is aligned with the evolution of the codebase.

Looking forward to your response.

Best regards,
Temitope Ogunleye

**Comment by Felipe-Perez-Ferraro** [comment]
Hi @topeogunleye, yes. Really sorry
This is the link, i have to submit in the microverse plataform?
[Link to the issue](https://github.com/MarcoDDM/recipe/issues/11)

**Comment by topeogunleye** [comment]
Hi @MarcoDDM, @Felipe-Perez-Ferraro,

While you've put in commendable effort into your project, I'm unable to proceed with the review.

## Invalid Code Review Request

It's essential to use the same Issue from your initial review request for re-reviews. Please, refer to the previous issue you used for the first review and request a re-review there. Additionally, I'll mark this Code Review Request as invalid.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
